spring:
  profiles:
    default: local

  application:
    name: issue-tracker-api

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      time-to-live: 5m

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    locations: classpath:db/migration

server:
  port: 8080
