spring:
  profiles:
    default: local

  application:
    name: issue-tracker-api

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    locations: classpath:db/migration

server:
  port: 8080
